# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
 - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: dotnet restor
  inputs:
    command: 'restore'
    projects: '**/CHIFA.Stat.csproj'
    feedsToUse: 'select'
    vstsFeed: '1ed0d063-2001-4386-82a2-66c01ee046b2'
      
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: '**/CHIFA.Stat.csproj'
    arguments: '--configuration Release  --no-restore --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'CHIFA.Stat'
    publishLocation: 'Container'