trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # Automatically increment the version number with each build

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/CHIFA.Stat.csproj'
    feedsToUse: 'select'
    vstsFeed: '1ed0d063-2001-4386-82a2-66c01ee046b2'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet build'
#   inputs:
#     command: 'build'
#     projects: '**/*.csproj'
#     arguments: '--configuration Release  --no-restore --output $(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName:  publish App
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    projects: '**/CHIFA.Stat.csproj'
    arguments: '-c Release --no-self-contained -r win-x64 -o $(Build.ArtifactStagingDirectory)/publish  --no-restore'

- task: DotNetCoreCLI@2
  displayName:  Install VPK
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global vpk'

- task: PowerShell@2
  displayName: 'Extract File Version'
  inputs:
    targetType: 'inline'
    script: |
      $filePath = "$(Build.ArtifactStagingDirectory)/publish/CHIFA.Stat.exe"  
      if (Test-Path $filePath) {
        $fullVersion = (Get-Item $filePath).VersionInfo.FileVersion
           # Extract the first three parts (MAJOR.MINOR.PATCH)
          $versionParts = $fullVersion -split '\.'  # Split the version string by '.'
          $major = [int]$versionParts[0]
          $minor = [int]$versionParts[1]
          $patch = [int]$versionParts[2]
          $shortVersion = "$major.$minor.$patch"  # Construct the new version string
          Write-Host "FileVersion: $shortVersion"
          Write-Output "##vso[task.setvariable variable=FileVersion]$shortVersion"
         } else {
           Write-Error "File not found: $filePath"
         } 

- task: PowerShell@2
  displayName: 'Download Update with VPK'
  inputs:
    targetType: 'inline'
    script: |
      $url = "https://nadirsmartapp.blob.core.windows.net/chifa-stat"
      vpk download http --url $url -o $(Build.ArtifactStagingDirectory)/Releases

- task: PowerShell@2
  displayName: Pack App using VPK
  inputs:
    targetType: 'inline'
    script: 'vpk pack -u CHIFA.Stat -v $(FileVersion) -p $(Build.ArtifactStagingDirectory)/publish --icon $(Build.ArtifactStagingDirectory)/publish/icon.ico  -e CHIFA.Stat.exe --outputDir $(Build.ArtifactStagingDirectory)/Releases'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Releases'
    ArtifactName: 'CHIFA.Stat'
    publishLocation: 'Container'

