trigger:
- Devlop

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  assembly: 'CHIFA.Server'
  project: '**/*$(assembly).csproj'
  # Automatically increment the version number with each build

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: $(project)
    feedsToUse: 'select'
    vstsFeed: '1ed0d063-2001-4386-82a2-66c01ee046b2'

- task: DotNetCoreCLI@2
  displayName:  Publish App
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    projects: $(project)
    arguments: '-c Release --no-self-contained -r win-x64 -o $(Build.ArtifactStagingDirectory)/publish  --no-restore'

- task: DotNetCoreCLI@2
  displayName:  Install VPK
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global vpk'

- task: PowerShell@2
  displayName: 'Extract File Version'
  inputs:
    targetType: 'inline'
    script: |
      $filePath = "$(Build.ArtifactStagingDirectory)/publish/$(assembly).exe"  
      if (Test-Path $filePath) {
        $fullVersion = (Get-Item $filePath).VersionInfo.FileVersion
           # Extract the first three parts (MAJOR.MINOR.PATCH)
          $versionParts = $fullVersion -split '\.'  # Split the version string by '.'
          $major = $versionParts[0]
          $minor = $versionParts[1]
          $patch = $versionParts[2]
          $shortVersion = "$major.$minor.$patch"  # Construct the new version string
          Write-Host "FileVersion: $shortVersion"
          Write-Output "##vso[task.setvariable variable=FileVersion]$shortVersion"
         } else {
           Write-Error "File not found: $filePath"
         } 

- task: PowerShell@2
  displayName: 'Download Update with VPK'
  inputs:
    targetType: 'inline'
    script: |
      $url = "https://nadirsmartapp.blob.core.windows.net/chifa-server"
      vpk download http --url $url -o $(Build.ArtifactStagingDirectory)/Releases

- task: PowerShell@2
  displayName: Pack App using VPK
  inputs:
    targetType: 'inline'
    script: 'vpk pack -u $(assembly) -v $(FileVersion) -p $(Build.ArtifactStagingDirectory)/publish --icon $(Build.ArtifactStagingDirectory)/publish/icon.ico  -e $(assembly).exe --outputDir $(Build.ArtifactStagingDirectory)/Releases'


- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Releases'
    ArtifactName: '$(assembly)'
    publishLocation: 'Container'

