<Project Sdk="Microsoft.NET.Sdk">
 	<PropertyGroup>
 		<TargetFramework>net10.0-windows</TargetFramework>
 		<OutputType>WinExe</OutputType>
 		<UseWindowsForms>true</UseWindowsForms>
 		<RootNamespace>CHIFA.Pro</RootNamespace>
   		<StartupObject>CHIFA.Pro.Program</StartupObject>
  		<Product>CHIFA.Pro</Product>
  		<ApplicationIcon>Assets\Icon.ico</ApplicationIcon>
  		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<WarningsAsErrors>DX1000;DX1001</WarningsAsErrors>
		<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="FodyWeavers.xml" />
		<None Remove="FodyWeavers.xsd" />
		<None Remove="Icon.ico" />
	</ItemGroup>
	 
	<ItemGroup>
		<Content Include="Assets\Icon.ico" />
		<Content Include="Icon.ico">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	 
	<ItemGroup>
	  <PackageReference Include="DevExpress.Win.Design" Version="26.1.3" />
	  <PackageReference Include="Npgsql" Version="10.*" />
	  <PackageReference Include="QRCoder" Version="1.*" />
	  <PackageReference Include="ReportViewerCore.WinForms" Version="15.*" />
	  <PackageReference Include="Serilog.Sinks.Debug" Version="3.*" />
	  <PackageReference Include="Serilog.Sinks.File" Version="7.*" />
	  <PackageReference Include="SmartApp.Telemetry.Client" Version="1.*" />
	  <PackageReference Include="Velopack" Version="1.2.0" />
	  <PackageReference Include="ZXing.Net" Version="0.16.*" />
	  <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.*" />
 	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Reports\Facture.rdlc" />
	  <EmbeddedResource Include="Reports\Verso_Ord.rdlc" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Reports\Facture.rdlc" />
	  <None Remove="Reports\Verso_Ord.rdlc" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CHIFA.Services\CHIFA.Services.csproj" />
	</ItemGroup>

</Project>