<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>WinExe</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>CHIFA.Pro</RootNamespace>
		<LangVersion>preview</LangVersion>
		<Authors>MEZHOUDI Hadj Nadir</Authors>
		<Company>SmartApps</Company>
		<Product>CHIFA Pro</Product>
		<PackageId>CHIFA Pro</PackageId>
		<PackageIcon>Icon.ico</PackageIcon>
		<StartupObject>CHIFA.Pro.Program</StartupObject>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<ApplicationIcon>Assets\Icon.ico</ApplicationIcon>
		<ImplicitUsings>true</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>1.0.91</Version>
		<AssemblyInformationalVersion>1.0.91</AssemblyInformationalVersion>
		<SatelliteResourceLanguages>ar</SatelliteResourceLanguages>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="FodyWeavers.xml" />
		<None Remove="FodyWeavers.xsd" />
	</ItemGroup>


	<ItemGroup>
		<Content Include="Assets\Icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DevExpress.Win.Design" Version="24.1.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CHIFA.DAL\CHIFA.DAL.csproj" />
	</ItemGroup>

</Project>