<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CHIFA.DAL\CHIFA.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.*" />
    <PackageReference Include="Grpc.Core" Version="2.*" />
    <PackageReference Include="protobuf-net.Grpc.Native" Version="1.*" />
    <PackageReference Include="ReusableTheme" Version="2.*" />
    <PackageReference Include="Serilog" Version="4.*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.*" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.*" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.*" />
    <PackageReference Include="SmartApp.Bridge" Version="2.11.3.2011" />
    <PackageReference Include="Velopack" Version="0.*" />
  </ItemGroup>

  <ItemGroup>
    <None Update="icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
