<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
	<ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>
 
  <ItemGroup>
	  <PackageReference Include="CHIFA2.Data" Version="1.0.*" />
  </ItemGroup>

</Project>
