<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CHIFA2.Data" Version="2.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CHIFA.Contract\CHIFA.Contract.csproj" />
	</ItemGroup>

</Project>
