<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<StartupObject>CHIFA.Tests.Program</StartupObject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.*" />
		<PackageReference Include="CHIFA2.Data" Version="2.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CHIFA Pro\CHIFA.Pro.csproj" />
		<ProjectReference Include="..\CHIFA.DAL\CHIFA.DAL.csproj" />
		<ProjectReference Include="..\CHIFA.Stat\CHIFA.Stat.csproj" />
	</ItemGroup>

</Project>
