<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>

	  <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="protobuf-net.Grpc" Version="1.*" />
		<PackageReference Include="CHIFA2.Data" Version="2.*" />
	</ItemGroup>

</Project>
